param(
  [string]$RepoToken = $env:GITHUB_TOKEN,
  [string]$Owner = '',
  [string]$Repo = ''
)

# Create a GitHub issue for quota requests from the artifacts/quota-requests/*.json files.
# Used when the team cannot auto-submit support tickets (fallback option).

if (-not $RepoToken) { Write-Error 'GITHUB_TOKEN env var not set'; exit 1 }
if (-not $Owner -or -not $Repo) { Write-Error 'Owner and Repo must be set'; exit 1 }

$artDir = Join-Path (Get-Location) 'artifacts\quota-requests'
if (-not (Test-Path $artDir)) { Write-Error "Artifacts folder not found: $artDir"; exit 1 }

$summaryFile = Get-ChildItem -Path $artDir -Filter 'quota-request-summary-*.md' -File | Sort-Object CreationTime -Descending | Select-Object -First 1
if (-not $summaryFile) { Write-Error 'No quota request summary found'; exit 1 }

$summary = Get-Content $summaryFile.FullName -Raw
$time = Get-Date -Format 'yyyy-MM-dd HH:mm:ss'
$title = "Quota Request - $time"

$body = @"
## Quota Request

Generated on $time

$summary

### Artifacts
Attached JSON files in artifacts/quota-requests/ folder:
"@

$jsonFiles = Get-ChildItem -Path $artDir -Filter 'quota-request-*.json' -File
foreach ($f in $jsonFiles) {
  $body += "`n- $($f.Name)"
}

$body += @"

## Next Steps
1. Review the quota requirements above
2. If using Azure Portal: Help + support → New support request → Quotas
3. If using CLI (with permissions): Run `pwsh ./scripts/submit-azure-support-ticket.ps1 -ContactName 'Your Name' -ContactEmail 'you@example.com' -AutoConfirm`

---
_This issue was auto-generated by the azure-quota verification workflow._
"@

$uri = "https://api.github.com/repos/$Owner/$Repo/issues"
$headers = @{
  Authorization = "token $RepoToken"
  'Content-Type' = 'application/json'
}

$payload = @{
  title = $title
  body = $body
  labels = @('quota-request', 'azure')
} | ConvertTo-Json -Depth 10

Write-Host "Creating GitHub issue in $Owner/$Repo"
$resp = Invoke-WebRequest -Uri $uri -Method Post -Headers $headers -Body $payload -ErrorAction Stop
$issue = $resp.Content | ConvertFrom-Json

Write-Host "Created issue #$($issue.number): $($issue.html_url)"
exit 0
