param(
  [string]$ContactName = '',
  [string]$ContactEmail = '',
  [string]$Severity = 'moderate',
  [switch]$AutoConfirm
)

# Submit an Azure support ticket using Microsoft.Support REST API.
# The script reads artifacts/quota-requests/*.json and generates a consolidated ticket.
# Requires appropriate permissions (Microsoft.Support/supportTickets/*) for the authenticated principal.

$sub = az account show --query id -o tsv
if (-not $sub) { Write-Error 'Unable to determine subscription id. Ensure az is logged in.'; exit 3 }

$artDir = Join-Path (Get-Location) 'artifacts\quota-requests'
if (-not (Test-Path $artDir)) { Write-Error "Artifacts folder not found: $artDir"; exit 3 }

$jsonFiles = Get-ChildItem -Path $artDir -Filter 'quota-request-*.json' -File -ErrorAction SilentlyContinue
if (-not $jsonFiles -or $jsonFiles.Count -eq 0) { Write-Error 'No quota-request JSON artifacts found to submit.'; exit 3 }

# Build ticket content
$time = Get-Date -Format 'yyyy-MM-dd HH:mm:ss'
$titleParts = @()
$descSb = New-Object System.Text.StringBuilder
$descSb.AppendLine("Quota increase request generated by azure-quota script on $time") | Out-Null
$descSb.AppendLine('') | Out-Null

foreach ($f in $jsonFiles) {
  $content = Get-Content $f.FullName -Raw
  $obj = $null
  try { $obj = $content | ConvertFrom-Json -ErrorAction Stop } catch { $obj = @{ raw = $content } }
  $resName = ($obj.resource -as [string]) -or ($f.BaseName -replace 'quota-request-','')
  $titleParts += $resName
  $descSb.AppendLine("---") | Out-Null
  $descSb.AppendLine("File: $($f.Name)") | Out-Null
  $descSb.AppendLine('```json') | Out-Null
  $descSb.AppendLine($content) | Out-Null
  $descSb.AppendLine('```') | Out-Null
}

$title = "Quota increase request: " + ($titleParts -join ', ')
$description = $descSb.ToString()

# Discover Microsoft Support services to choose a serviceId
Write-Host 'Discovering Microsoft Support services (this may take a moment)'
$servicesOut = az rest --method get --uri "https://management.azure.com/providers/Microsoft.Support/services?api-version=2019-05-01" -o json 2>&1
if ($LASTEXITCODE -ne 0) { Write-Warning "Failed to list support services: $servicesOut"; $services = @() } else { try { $services = $servicesOut | ConvertFrom-Json } catch { Write-Warning 'Failed to parse services response'; $services = @() } }

# Simple mapping heuristics to pick a serviceId
function Pick-ServiceIdForResource($resourceName){
  $lookup = $resourceName.ToLower()
  foreach ($s in $services.value) {
    $n = ($s.properties.displayName -as [string]) -or $s.name
    if ($n -and $n.ToLower().Contains('compute') -and $lookup.Contains('vcpu')) { return $s.id }
    if ($n -and $n.ToLower().Contains('virtual machine') -and $lookup.Contains('vcpu')) { return $s.id }
    if ($n -and ($n.ToLower().Contains('app service') -or $n.ToLower().Contains('web')) -and $lookup.Contains('appservice')) { return $s.id }
    if ($n -and ($n.ToLower().Contains('kubernetes') -or $n.ToLower().Contains('container')) -and $lookup.Contains('aks')) { return $s.id }
    if ($n -and $n.ToLower().Contains('network') -and $lookup.Contains('publicip')) { return $s.id }
  }
  # fallback to first service if available
  if ($services.value -and $services.value.Count -gt 0) { return $services.value[0].id }
  return $null
}

# Choose a service id based on the first artifact name
$firstRes = ($jsonFiles[0].BaseName -replace 'quota-request-','')
$serviceId = Pick-ServiceIdForResource($firstRes)
if (-not $serviceId) { Write-Warning 'Could not pick a support service id automatically; you may need to open the portal manually'; exit 4 }

# Parse contact name
$firstName = '' ; $lastName = '';
if ($ContactName -ne '') {
  $parts = $ContactName.Split(' ',2)
  $firstName = $parts[0]
  if ($parts.Count -gt 1) { $lastName = $parts[1] }
}

if (-not $ContactEmail -or $ContactEmail -eq '') { Write-Warning 'No contact email provided; support may reject the ticket.' }

$ticketName = "quota-" + (Get-Date -Format 'yyyyMMddHHmmss')
$uri = "https://management.azure.com/subscriptions/$sub/providers/Microsoft.Support/supportTickets/$ticketName?api-version=2019-05-01"

$body = @{
  location = 'global'
  properties = @{
    title = $title
    description = $description
    serviceId = $serviceId
    severity = $Severity
    contactDetails = @{
      firstName = $firstName
      lastName = $lastName
      email = $ContactEmail
      phone = ''
      preferredContactMethod = 'email'
    }
  }
}

$bodyJson = $body | ConvertTo-Json -Depth 10

Write-Host "Prepared support ticket payload. Endpoint: $uri"
if (-not $AutoConfirm) {
  Write-Host 'Run the script with -AutoConfirm to submit without prompting.'
  $ok = Read-Host 'Proceed to create support ticket? (y/N)'
  if ($ok.ToLower() -ne 'y') { Write-Host 'Aborting'; exit 0 }
}

Write-Host 'Submitting support ticket...'
$resp = az rest --method put --uri $uri --body "$bodyJson" -o json 2>&1
if ($LASTEXITCODE -ne 0) { Write-Error "Failed to create support ticket: $resp"; exit 5 }
try { $r = $resp | ConvertFrom-Json; Write-Host 'Support ticket created:'; Write-Host ($r | ConvertTo-Json -Depth 5); exit 0 } catch { Write-Warning 'Ticket created but response parsing failed'; Write-Host $resp; exit 0 }